--i stole this from https://github.com/ellisonleao/gruvbox.nvim

local user = require("user")

local Pita = {}

Pita.config = {
  terminal_colors = true,
  undercurl = true,
  underline = true,
  bold = false,
  italic = {
    strings = true,
    emphasis = true,
    comments = true,
    operators = false,
    folds = true,
  },
  strikethrough = true,
  palette_overrides = {},
  overrides = {},
  dim_inactive = false,
  transparent_mode = false,
}



Pita.palette = {
  dark0 = user.colorscheme.dark0,
  dark0_soft = user.colorscheme.dark0_soft,
  dark1 = user.colorscheme.dark1,
  dark2 = user.colorscheme.dark2,
  dark3 = user.colorscheme.dark3,
  dark4 = user.colorscheme.dark4,

  light0_hard = user.colorscheme.light0_hard,
  light0 = user.colorscheme.light0,
  light0_soft = user.colorscheme.light0_soft,
  light1 = user.colorscheme.light1,
  light2 = user.colorscheme.light2,
  light3 = user.colorscheme.light3,
  light4 = user.colorscheme.light4,

  red = user.colorscheme.red,
  green = user.colorscheme.green,
  yellow = user.colorscheme.yellow,
  blue = user.colorscheme.blue,
  purple = user.colorscheme.purple,
  aqua = user.colorscheme.aqua,
  orange = user.colorscheme.orange,
  gray = user.colorscheme.gray,


}



--i stole this from https://github.com/ellisonleao/gruvbox.nvim
local function get_colors()
  local p = Pita.palette
  local config = Pita.config

  for color, hex in pairs(config.palette_overrides) do
    p[color] = hex
  end

  local bg = vim.o.background

  local color_groups = {
    dark = {
      bg0 = p.dark0,
      bg1 = p.dark1,
      bg2 = p.dark2,
      bg3 = p.dark3,
      bg4 = p.dark4,
      fg0 = p.light0,
      fg1 = p.light1,
      fg2 = p.light2,
      fg3 = p.light3,
      fg4 = p.light4,
      red = p.red,
      green = p.green,
      yellow = p.yellow,
      blue = p.blue,
      purple = p.purple,
      aqua = p.aqua,
      orange = p.orange,
      faded_red = p.red,
      faded_green = p.green,
      faded_yellow = p.yellow,
      faded_blue = p.blue,
      faded_purple = p.purple,
      faded_aqua = p.aqua,
      gray = p.gray,
    },
  }
  return color_groups[bg]
end

local function get_groups()
  local colors = get_colors()
  local config = Pita.config

  if config.terminal_colors then
    local term_colors = {
      colors.bg0,
      colors.faded_red,
      colors.faded_green,
      colors.faded_yellow,
      colors.faded_blue,
      colors.faded_purple,
      colors.faded_aqua,
      colors.fg4,
      colors.gray,
      colors.red,
      colors.green,
      colors.yellow,
      colors.blue,
      colors.purple,
      colors.aqua,
      colors.fg1,
    }
    for index, value in ipairs(term_colors) do
      vim.g["terminal_color_" .. index - 1] = value
    end
  end

  local groups = {
    pitaFg0 = { fg = colors.fg0 },
    pitaFg1 = { fg = colors.fg1 },
    pitaFg2 = { fg = colors.fg2 },
    pitaFg3 = { fg = colors.fg3 },
    pitaFg4 = { fg = colors.fg4 },
    pitaGray = { fg = colors.gray },
    pitaBg0 = { fg = colors.bg0 },
    pitaBg1 = { fg = colors.bg1 },
    pitaBg2 = { fg = colors.bg2 },
    pitaBg3 = { fg = colors.bg3 },
    pitaBg4 = { fg = colors.bg4 },
    pitaRed = { fg = colors.red },
    pitaRedBold = { fg = colors.red, bold = config.bold },
    pitaGreen = { fg = colors.green },
    pitaGreenBold = { fg = colors.green, bold = config.bold },
    pitaYellow = { fg = colors.yellow },
    pitaYellowBold = { fg = colors.yellow, bold = config.bold },
    pitaBlue = { fg = colors.blue },
    pitaBlueBold = { fg = colors.blue, bold = config.bold },
    pitaPurple = { fg = colors.purple },
    pitaPurpleBold = { fg = colors.purple, bold = config.bold },
    pitaAqua = { fg = colors.aqua },
    pitaAquaBold = { fg = colors.aqua, bold = config.bold },
    pitaOrange = { fg = colors.orange },
    pitaOrangeBold = { fg = colors.orange, bold = config.bold },
    pitaRedSign = config.transparent_mode and { fg = colors.red, }
        or { fg = colors.red, bg = colors.bg1, },
    pitaGreenSign = config.transparent_mode and { fg = colors.green, }
        or { fg = colors.green, bg = colors.bg1, },
    pitaYellowSign = config.transparent_mode and { fg = colors.yellow, }
        or { fg = colors.yellow, bg = colors.bg1, },
    pitaBlueSign = config.transparent_mode and { fg = colors.blue, }
        or { fg = colors.blue, bg = colors.bg1, },
    pitaPurpleSign = config.transparent_mode and { fg = colors.purple, }
        or { fg = colors.purple, bg = colors.bg1, },
    pitaAquaSign = config.transparent_mode and { fg = colors.aqua, }
        or { fg = colors.aqua, bg = colors.bg1, },
    pitaOrangeSign = config.transparent_mode and { fg = colors.orange, }
        or { fg = colors.orange, bg = colors.bg1, },
    pitaRedUnderline = { undercurl = config.undercurl, sp = colors.red },
    pitaGreenUnderline = { undercurl = config.undercurl, sp = colors.green },
    pitaYellowUnderline = { undercurl = config.undercurl, sp = colors.yellow },
    pitaBlueUnderline = { undercurl = config.undercurl, sp = colors.blue },
    pitaPurpleUnderline = { undercurl = config.undercurl, sp = colors.purple },
    pitaAquaUnderline = { undercurl = config.undercurl, sp = colors.aqua },
    pitaOrangeUnderline = { undercurl = config.undercurl, sp = colors.orange },
    Normal = config.transparent_mode and { fg = colors.fg1, bg = nil } or { fg = colors.fg1, bg = colors.bg0 },
    NormalFloat = config.transparent_mode and { fg = colors.fg1, bg = nil } or { fg = colors.fg1, bg = colors.bg1 },
    NormalNC = config.dim_inactive and { fg = colors.fg0, bg = colors.bg1 } or { link = "Normal" },
    CursorLine = { bg = colors.bg1 },
    CursorColumn = { link = "CursorLine" },
    TabLineFill = { fg = colors.bg2, bg = colors.bg, },
    TabLineSel = { fg = colors.fg0, bg = colors.bg0, },
    TabLine = { link = "TabLineFill" },
    MatchParen = { bg = colors.bg3, bold = config.bold },
    ColorColumn = { bg = colors.bg1 },
    Conceal = { fg = colors.blue },
    CursorLineNr = { fg = colors.blue, bg = colors.bg },
    NonText = { link = "pitaBg2" },
    SpecialKey = { link = "pitaFg4" },
    Visual = { bg = colors.bg3, },
    VisualNOS = { link = "Visual" },
    Search = { fg = colors.yellow, bg = colors.bg0, },
    IncSearch = { fg = colors.orange, bg = colors.bg0, },
    CurSearch = { link = "IncSearch" },
    QuickFixLine = { link = "pitaPurple" },
    Underlined = { fg = colors.blue, underline = config.underline },
    StatusLine = { fg = colors.bg2, bg = colors.fg1, },
    StatusLineNC = { fg = colors.bg1, bg = colors.fg4, },
    WinBar = { fg = colors.fg4, bg = colors.bg0 },
    WinBarNC = { fg = colors.fg3, bg = colors.bg1 },
    WinSeparator = config.transparent_mode and { fg = colors.bg3, bg = nil } or { fg = colors.bg3, bg = colors.bg0 },
    WildMenu = { fg = colors.blue, bg = colors.bg2, bold = config.bold },
    Directory = { link = "pitaGreenBold" },
    Title = { link = "pitaGreenBold" },
    ErrorMsg = { fg = colors.bg0, bg = colors.red, bold = config.bold },
    MoreMsg = { link = "pitaYellowBold" },
    ModeMsg = { link = "pitaYellowBold" },
    Question = { link = "pitaOrangeBold" },
    WarningMsg = { link = "pitaRedBold" },
    LineNr = { fg = colors.bg4 },
    SignColumn = { bg = colors.bg0 },
    Folded = { fg = colors.gray, bg = colors.bg1, italic = config.italic.folds },
    FoldColumn = config.transparent_mode and { fg = colors.gray, bg = nil } or { fg = colors.gray, bg = colors.bg1 },
    vCursor = { link = "Cursor" },
    iCursor = { link = "Cursor" },
    lCursor = { link = "Cursor" },
    Special = { link = "pitaOrange" },
    Comment = { fg = colors.gray, italic = config.italic.comments },
    Todo = { fg = colors.bg0, bg = colors.yellow, bold = config.bold, italic = config.italic.comments },
    Done = { fg = colors.orange, bold = config.bold, italic = config.italic.comments },
    Error = { fg = colors.red, bold = config.bold, },
    Statement = { link = "pitaRed" },
    Conditional = { link = "pitaRed" },
    Repeat = { link = "pitaRed" },
    Label = { link = "pitaRed" },
    Exception = { link = "pitaRed" },
    Operator = { fg = colors.orange, italic = config.italic.operators },
    Keyword = { link = "pitaRed" },
    Identifier = { link = "pitaBlue" },
    Function = { link = "pitaGreenBold" },
    PreProc = { link = "pitaAqua" },
    Include = { link = "pitaAqua" },
    Define = { link = "pitaAqua" },
    Macro = { link = "pitaAqua" },
    PreCondit = { link = "pitaAqua" },
    Constant = { link = "pitaPurple" },
    Character = { link = "pitaPurple" },
    String = { fg = colors.green, italic = config.italic.strings },
    Boolean = { link = "pitaPurple" },
    Number = { link = "pitaPurple" },
    Float = { link = "pitaPurple" },
    Type = { link = "pitaYellow" },
    StorageClass = { link = "pitaOrange" },
    Structure = { link = "pitaAqua" },
    Typedef = { link = "pitaYellow" },
    Pmenu = { fg = colors.fg1, bg = colors.bg1 },
    PmenuSel = { fg = colors.bg1, bg = colors.bg3, bold = config.bold },
    PmenuKindSel = { fg = colors.bg1, bg = colors.bg3, bold = config.bold },
    PmenuSbar = { bg = colors.bg1 },
    PmenuThumb = { bg = colors.bg1 },
    DiffDelete = { bg = colors.faded_red },
    DiffAdd = { bg = colors.faded_green },
    DiffChange = { bg = colors.faded_aqua },
    DiffText = { bg = colors.yellow, fg = colors.bg0 },
    SpellCap = { link = "pitaBlueUnderline" },
    SpellBad = { link = "pitaRedUnderline" },
    SpellLocal = { link = "pitaAquaUnderline" },
    SpellRare = { link = "pitaPurpleUnderline" },
    Whitespace = { fg = colors.bg2 },
    Delimiter = { link = "pitaBlue" },
    EndOfBuffer = { link = "NonText" },
    DiagnosticError = { link = "pitaRed" },
    DiagnosticSignError = { fg = colors.red, bg = colors.bg0 },
    DiagnosticUnderlineError = { link = "pitaRedUnderline" },
    DiagnosticWarn = { link = "pitaYellow" },
    DiagnosticSignWarn = { fg = colors.yellow, bg = colors.bg0 },
    DiagnosticUnderlineWarn = { link = "pitaYellowUnderline" },
    DiagnosticInfo = { link = "pitaBlue" },
    DiagnosticSignInfo = { fg = colors.yellow, bg = colors.bg0 },
    DiagnosticUnderlineInfo = { link = "pitaBlueUnderline" },
    DiagnosticHint = { link = "pitaAqua" },
    DiagnosticSignHint = { fg = colors.aqua, bg = colors.bg0 },
    DiagnosticUnderlineHint = { link = "pitaAquaUnderline" },
    DiagnosticFloatingError = { link = "pitaRed" },
    DiagnosticFloatingWarn = { link = "pitaOrange" },
    DiagnosticFloatingInfo = { link = "pitaBlue" },
    DiagnosticFloatingHint = { link = "pitaAqua" },
    DiagnosticVirtualTextError = { link = "pitaRed" },
    DiagnosticVirtualTextWarn = { link = "pitaYellow" },
    DiagnosticVirtualTextInfo = { link = "pitaBlue" },
    DiagnosticVirtualTextHint = { link = "pitaAqua" },
    DiagnosticOk = { link = "pitaGreenSign" },
    LspReferenceRead = { link = "pitaYellowBold" },
    LspReferenceText = { link = "pitaYellowBold" },
    LspReferenceWrite = { link = "pitaOrangeBold" },
    LspCodeLens = { link = "pitaGray" },
    LspSignatureActiveParameter = { link = "Search" },
    gitcommitSelectedFile = { link = "pitaGreen" },
    gitcommitDiscardedFile = { link = "pitaRed" },
    GitSignsAdd = { link = "pitaGreen" },
    GitSignsChange = { link = "pitaOrange" },
    GitSignsDelete = { link = "pitaRed" },
    NvimTreeSymlink = { fg = colors.faded_aqua },
    NvimTreeRootFolder = { fg = colors.faded_purple, bold = true },
    NvimTreeFolderIcon = { fg = colors.faded_blue, bold = true },
    NvimTreeFileIcon = { fg = colors.light2 },
    NvimTreeExecFile = { fg = colors.faded_green, bold = true },
    NvimTreeOpenedFile = { fg = colors.red, bold = true },
    NvimTreeSpecialFile = { fg = colors.faded_yellow, bold = true, underline = true },
    NvimTreeImageFile = { fg = colors.faded_purple },
    NvimTreeIndentMarker = { fg = colors.dark3 },
    NvimTreeGitDirty = { fg = colors.faded_yellow },
    NvimTreeGitStaged = { fg = colors.faded_yellow },
    NvimTreeGitMerge = { fg = colors.faded_purple },
    NvimTreeGitRenamed = { fg = colors.faded_purple },
    NvimTreeGitNew = { fg = colors.faded_yellow },
    NvimTreeGitDeleted = { fg = colors.faded_red },
    NvimTreeWindowPicker = { bg = colors.aqua },
    debugPC = { link = "DiffAdd" },
    debugBreakpoint = { link = "pitaRedSign" },
    StartifyBracket = { link = "pitaFg3" },
    StartifyFile = { link = "pitaFg1" },
    StartifyNumber = { link = "pitaBlue" },
    StartifyPath = { link = "pitaGray" },
    StartifySlash = { link = "pitaGray" },
    StartifySection = { link = "pitaYellow" },
    StartifySpecial = { link = "pitaBg2" },
    StartifyHeader = { link = "pitaOrange" },
    StartifyFooter = { link = "pitaBg2" },
    StartifyVar = { link = "StartifyPath" },
    StartifySelect = { link = "Title" },
    DirvishPathTail = { link = "pitaAqua" },
    DirvishArg = { link = "pitaYellow" },
    netrwDir = { link = "pitaAqua" },
    netrwClassify = { link = "pitaAqua" },
    netrwLink = { link = "pitaGray" },
    netrwSymLink = { link = "pitaFg1" },
    netrwExe = { link = "pitaYellow" },
    netrwComment = { link = "pitaGray" },
    netrwList = { link = "pitaBlue" },
    netrwHelpCmd = { link = "pitaAqua" },
    netrwCmdSep = { link = "pitaFg3" },
    netrwVersion = { link = "pitaGreen" },
    NERDTreeDir = { link = "pitaAqua" },
    NERDTreeDirSlash = { link = "pitaAqua" },
    NERDTreeOpenable = { link = "pitaOrange" },
    NERDTreeClosable = { link = "pitaOrange" },
    NERDTreeFile = { link = "pitaFg1" },
    NERDTreeExecFile = { link = "pitaYellow" },
    NERDTreeUp = { link = "pitaGray" },
    NERDTreeCWD = { link = "pitaGreen" },
    NERDTreeHelp = { link = "pitaFg1" },
    NERDTreeToggleOn = { link = "pitaGreen" },
    NERDTreeToggleOff = { link = "pitaRed" },
    CocErrorSign = { link = "pitaRedSign" },
    CocWarningSign = { link = "pitaOrangeSign" },
    CocInfoSign = { link = "pitaBlueSign" },
    CocHintSign = { link = "pitaAquaSign" },
    CocErrorFloat = { link = "pitaRed" },
    CocWarningFloat = { link = "pitaOrange" },
    CocInfoFloat = { link = "pitaBlue" },
    CocHintFloat = { link = "pitaAqua" },
    CocDiagnosticsError = { link = "pitaRed" },
    CocDiagnosticsWarning = { link = "pitaOrange" },
    CocDiagnosticsInfo = { link = "pitaBlue" },
    CocDiagnosticsHint = { link = "pitaAqua" },
    CocSelectedText = { link = "pitaRed" },
    CocMenuSel = { link = "PmenuSel" },
    CocCodeLens = { link = "pitaGray" },
    CocErrorHighlight = { link = "pitaRedUnderline" },
    CocWarningHighlight = { link = "pitaOrangeUnderline" },
    CocInfoHighlight = { link = "pitaBlueUnderline" },
    CocHintHighlight = { link = "pitaAquaUnderline" },
    TelescopeNormal = { link = "pitaFg1" },
    TelescopeSelection = { link = "pitaOrangeBold" },
    TelescopeSelectionCaret = { link = "pitaRed" },
    TelescopeMultiSelection = { link = "pitaGray" },
    TelescopeBorder = { link = "TelescopeNormal" },
    TelescopePromptBorder = { link = "TelescopeNormal" },
    TelescopeResultsBorder = { link = "TelescopeNormal" },
    TelescopePreviewBorder = { link = "TelescopeNormal" },
    TelescopeMatching = { link = "pitaBlue" },
    TelescopePromptPrefix = { link = "pitaRed" },
    TelescopePrompt = { link = "TelescopeNormal" },
    CmpItemAbbr = { link = "pitaFg0" },
    CmpItemAbbrDeprecated = { link = "pitaFg1" },
    CmpItemAbbrMatch = { link = "pitaBlueBold" },
    CmpItemAbbrMatchFuzzy = { link = "pitaBlueUnderline" },
    CmpItemMenu = { link = "pitaGray" },
    CmpItemKindText = { link = "pitaOrange" },
    CmpItemKindVariable = { link = "pitaOrange" },
    CmpItemKindMethod = { link = "pitaBlue" },
    CmpItemKindFunction = { link = "pitaBlue" },
    CmpItemKindConstructor = { link = "pitaYellow" },
    CmpItemKindUnit = { link = "pitaBlue" },
    CmpItemKindField = { link = "pitaBlue" },
    CmpItemKindClass = { link = "pitaYellow" },
    CmpItemKindInterface = { link = "pitaYellow" },
    CmpItemKindModule = { link = "pitaBlue" },
    CmpItemKindProperty = { link = "pitaBlue" },
    CmpItemKindValue = { link = "pitaOrange" },
    CmpItemKindEnum = { link = "pitaYellow" },
    CmpItemKindOperator = { link = "pitaYellow" },
    CmpItemKindKeyword = { link = "pitaPurple" },
    CmpItemKindEvent = { link = "pitaPurple" },
    CmpItemKindReference = { link = "pitaPurple" },
    CmpItemKindColor = { link = "pitaPurple" },
    CmpItemKindSnippet = { link = "pitaGreen" },
    CmpItemKindFile = { link = "pitaBlue" },
    CmpItemKindFolder = { link = "pitaBlue" },
    CmpItemKindEnumMember = { link = "pitaAqua" },
    CmpItemKindConstant = { link = "pitaOrange" },
    CmpItemKindStruct = { link = "pitaYellow" },
    CmpItemKindTypeParameter = { link = "pitaYellow" },
    diffAdded = { link = "DiffAdd" },
    diffRemoved = { link = "DiffDelete" },
    diffChanged = { link = "DiffChange" },
    diffFile = { link = "pitaOrange" },
    diffNewFile = { link = "pitaYellow" },
    diffOldFile = { link = "pitaOrange" },
    diffLine = { link = "pitaBlue" },
    diffIndexLine = { link = "diffChanged" },
    NavicIconsFile = { link = "pitaBlue" },
    NavicIconsModule = { link = "pitaOrange" },
    NavicIconsNamespace = { link = "pitaBlue" },
    NavicIconsPackage = { link = "pitaAqua" },
    NavicIconsClass = { link = "pitaYellow" },
    NavicIconsMethod = { link = "pitaBlue" },
    NavicIconsProperty = { link = "pitaAqua" },
    NavicIconsField = { link = "pitaPurple" },
    NavicIconsConstructor = { link = "pitaBlue" },
    NavicIconsEnum = { link = "pitaPurple" },
    NavicIconsInterface = { link = "pitaGreen" },
    NavicIconsFunction = { link = "pitaBlue" },
    NavicIconsVariable = { link = "pitaPurple" },
    NavicIconsConstant = { link = "pitaOrange" },
    NavicIconsString = { link = "pitaGreen" },
    NavicIconsNumber = { link = "pitaOrange" },
    NavicIconsBoolean = { link = "pitaOrange" },
    NavicIconsArray = { link = "pitaOrange" },
    NavicIconsObject = { link = "pitaOrange" },
    NavicIconsKey = { link = "pitaAqua" },
    NavicIconsNull = { link = "pitaOrange" },
    NavicIconsEnumMember = { link = "pitaYellow" },
    NavicIconsStruct = { link = "pitaPurple" },
    NavicIconsEvent = { link = "pitaYellow" },
    NavicIconsOperator = { link = "pitaRed" },
    NavicIconsTypeParameter = { link = "pitaRed" },
    NavicText = { link = "pitaWhite" },
    NavicSeparator = { link = "pitaWhite" },
    htmlTag = { link = "pitaAquaBold" },
    htmlEndTag = { link = "pitaAquaBold" },
    htmlTagName = { link = "pitaBlue" },
    htmlArg = { link = "pitaOrange" },
    htmlTagN = { link = "pitaFg1" },
    htmlSpecialTagName = { link = "pitaBlue" },
    htmlLink = { fg = colors.fg4, underline = config.underline },
    htmlSpecialChar = { link = "pitaRed" },
    htmlBold = { fg = colors.fg0, bg = colors.bg0, bold = config.bold },
    htmlBoldUnderline = { fg = colors.fg0, bg = colors.bg0, bold = config.bold, underline = config.underline },
    htmlBoldItalic = { fg = colors.fg0, bg = colors.bg0, bold = config.bold, italic = true },
    htmlBoldUnderlineItalic = {
      fg = colors.fg0,
      bg = colors.bg0,
      bold = config.bold,
      italic = true,
      underline = config.underline,
    },
    htmlUnderline = { fg = colors.fg0, bg = colors.bg0, underline = config.underline },
    htmlUnderlineItalic = {
      fg = colors.fg0,
      bg = colors.bg0,
      italic = true,
      underline = config.underline,
    },
    htmlItalic = { fg = colors.fg0, bg = colors.bg0, italic = true },
    xmlTag = { link = "pitaAquaBold" },
    xmlEndTag = { link = "pitaAquaBold" },
    xmlTagName = { link = "pitaBlue" },
    xmlEqual = { link = "pitaBlue" },
    docbkKeyword = { link = "pitaAquaBold" },
    xmlDocTypeDecl = { link = "pitaGray" },
    xmlDocTypeKeyword = { link = "pitaPurple" },
    xmlCdataStart = { link = "pitaGray" },
    xmlCdataCdata = { link = "pitaPurple" },
    dtdFunction = { link = "pitaGray" },
    dtdTagName = { link = "pitaPurple" },
    xmlAttrib = { link = "pitaOrange" },
    xmlProcessingDelim = { link = "pitaGray" },
    dtdParamEntityPunct = { link = "pitaGray" },
    dtdParamEntityDPunct = { link = "pitaGray" },
    xmlAttribPunct = { link = "pitaGray" },
    xmlEntity = { link = "pitaRed" },
    xmlEntityPunct = { link = "pitaRed" },
    clojureKeyword = { link = "pitaBlue" },
    clojureCond = { link = "pitaOrange" },
    clojureSpecial = { link = "pitaOrange" },
    clojureDefine = { link = "pitaOrange" },
    clojureFunc = { link = "pitaYellow" },
    clojureRepeat = { link = "pitaYellow" },
    clojureCharacter = { link = "pitaAqua" },
    clojureStringEscape = { link = "pitaAqua" },
    clojureException = { link = "pitaRed" },
    clojureRegexp = { link = "pitaAqua" },
    clojureRegexpEscape = { link = "pitaAqua" },
    clojureRegexpCharClass = { fg = colors.fg3, bold = config.bold },
    clojureRegexpMod = { link = "clojureRegexpCharClass" },
    clojureRegexpQuantifier = { link = "clojureRegexpCharClass" },
    clojureParen = { link = "pitaFg3" },
    clojureAnonArg = { link = "pitaYellow" },
    clojureVariable = { link = "pitaBlue" },
    clojureMacro = { link = "pitaOrange" },
    clojureMeta = { link = "pitaYellow" },
    clojureDeref = { link = "pitaYellow" },
    clojureQuote = { link = "pitaYellow" },
    clojureUnquote = { link = "pitaYellow" },
    cOperator = { link = "pitaPurple" },
    cppOperator = { link = "pitaPurple" },
    cStructure = { link = "pitaOrange" },
    pythonBuiltin = { link = "pitaOrange" },
    pythonBuiltinObj = { link = "pitaOrange" },
    pythonBuiltinFunc = { link = "pitaOrange" },
    pythonFunction = { link = "pitaAqua" },
    pythonDecorator = { link = "pitaRed" },
    pythonInclude = { link = "pitaBlue" },
    pythonImport = { link = "pitaBlue" },
    pythonRun = { link = "pitaBlue" },
    pythonCoding = { link = "pitaBlue" },
    pythonOperator = { link = "pitaRed" },
    pythonException = { link = "pitaRed" },
    pythonExceptions = { link = "pitaPurple" },
    pythonBoolean = { link = "pitaPurple" },
    pythonDot = { link = "pitaFg3" },
    pythonConditional = { link = "pitaRed" },
    pythonRepeat = { link = "pitaRed" },
    pythonDottedName = { link = "pitaGreenBold" },
    cssBraces = { link = "pitaBlue" },
    cssFunctionName = { link = "pitaYellow" },
    cssIdentifier = { link = "pitaOrange" },
    cssClassName = { link = "pitaGreen" },
    cssColor = { link = "pitaBlue" },
    cssSelectorOp = { link = "pitaBlue" },
    cssSelectorOp2 = { link = "pitaBlue" },
    cssImportant = { link = "pitaGreen" },
    cssVendor = { link = "pitaFg1" },
    cssTextProp = { link = "pitaAqua" },
    cssAnimationProp = { link = "pitaAqua" },
    cssUIProp = { link = "pitaYellow" },
    cssTransformProp = { link = "pitaAqua" },
    cssTransitionProp = { link = "pitaAqua" },
    cssPrintProp = { link = "pitaAqua" },
    cssPositioningProp = { link = "pitaYellow" },
    cssBoxProp = { link = "pitaAqua" },
    cssFontDescriptorProp = { link = "pitaAqua" },
    cssFlexibleBoxProp = { link = "pitaAqua" },
    cssBorderOutlineProp = { link = "pitaAqua" },
    cssBackgroundProp = { link = "pitaAqua" },
    cssMarginProp = { link = "pitaAqua" },
    cssListProp = { link = "pitaAqua" },
    cssTableProp = { link = "pitaAqua" },
    cssFontProp = { link = "pitaAqua" },
    cssPaddingProp = { link = "pitaAqua" },
    cssDimensionProp = { link = "pitaAqua" },
    cssRenderProp = { link = "pitaAqua" },
    cssColorProp = { link = "pitaAqua" },
    cssGeneratedContentProp = { link = "pitaAqua" },
    javaScriptBraces = { link = "pitaFg1" },
    javaScriptFunction = { link = "pitaAqua" },
    javaScriptIdentifier = { link = "pitaRed" },
    javaScriptMember = { link = "pitaBlue" },
    javaScriptNumber = { link = "pitaPurple" },
    javaScriptNull = { link = "pitaPurple" },
    javaScriptParens = { link = "pitaFg3" },
    typescriptReserved = { link = "pitaAqua" },
    typescriptLabel = { link = "pitaAqua" },
    typescriptFuncKeyword = { link = "pitaAqua" },
    typescriptIdentifier = { link = "pitaOrange" },
    typescriptBraces = { link = "pitaFg1" },
    typescriptEndColons = { link = "pitaFg1" },
    typescriptDOMObjects = { link = "pitaFg1" },
    typescriptAjaxMethods = { link = "pitaFg1" },
    typescriptLogicSymbols = { link = "pitaFg1" },
    typescriptDocSeeTag = { link = "Comment" },
    typescriptDocParam = { link = "Comment" },
    typescriptDocTags = { link = "vimCommentTitle" },
    typescriptGlobalObjects = { link = "pitaFg1" },
    typescriptParens = { link = "pitaFg3" },
    typescriptOpSymbols = { link = "pitaFg3" },
    typescriptHtmlElemProperties = { link = "pitaFg1" },
    typescriptNull = { link = "pitaPurple" },
    typescriptInterpolationDelimiter = { link = "pitaAqua" },
    purescriptModuleKeyword = { link = "pitaAqua" },
    purescriptModuleName = { link = "pitaFg1" },
    purescriptWhere = { link = "pitaAqua" },
    purescriptDelimiter = { link = "pitaFg4" },
    purescriptType = { link = "pitaFg1" },
    purescriptImportKeyword = { link = "pitaAqua" },
    purescriptHidingKeyword = { link = "pitaAqua" },
    purescriptAsKeyword = { link = "pitaAqua" },
    purescriptStructure = { link = "pitaAqua" },
    purescriptOperator = { link = "pitaBlue" },
    purescriptTypeVar = { link = "pitaFg1" },
    purescriptConstructor = { link = "pitaFg1" },
    purescriptFunction = { link = "pitaFg1" },
    purescriptConditional = { link = "pitaOrange" },
    purescriptBacktick = { link = "pitaOrange" },
    coffeeExtendedOp = { link = "pitaFg3" },
    coffeeSpecialOp = { link = "pitaFg3" },
    coffeeCurly = { link = "pitaOrange" },
    coffeeParen = { link = "pitaFg3" },
    coffeeBracket = { link = "pitaOrange" },
    rubyStringDelimiter = { link = "pitaGreen" },
    rubyInterpolationDelimiter = { link = "pitaAqua" },
    rubyDefinedOperator = { link = "rubyKeyword" },
    objcTypeModifier = { link = "pitaRed" },
    objcDirective = { link = "pitaBlue" },
    goDirective = { link = "pitaAqua" },
    goConstants = { link = "pitaPurple" },
    goDeclaration = { link = "pitaRed" },
    goDeclType = { link = "pitaBlue" },
    goBuiltins = { link = "pitaOrange" },
    luaIn = { link = "pitaRed" },
    luaFunction = { link = "pitaAqua" },
    luaTable = { link = "pitaOrange" },
    moonSpecialOp = { link = "pitaFg3" },
    moonExtendedOp = { link = "pitaFg3" },
    moonFunction = { link = "pitaFg3" },
    moonObject = { link = "pitaYellow" },
    javaAnnotation = { link = "pitaBlue" },
    javaDocTags = { link = "pitaAqua" },
    javaCommentTitle = { link = "vimCommentTitle" },
    javaParen = { link = "pitaFg3" },
    javaParen1 = { link = "pitaFg3" },
    javaParen2 = { link = "pitaFg3" },
    javaParen3 = { link = "pitaFg3" },
    javaParen4 = { link = "pitaFg3" },
    javaParen5 = { link = "pitaFg3" },
    javaOperator = { link = "pitaOrange" },
    javaVarArg = { link = "pitaGreen" },
    elixirDocString = { link = "Comment" },
    elixirStringDelimiter = { link = "pitaGreen" },
    elixirInterpolationDelimiter = { link = "pitaAqua" },
    elixirModuleDeclaration = { link = "pitaYellow" },
    scalaNameDefinition = { link = "pitaFg1" },
    scalaCaseFollowing = { link = "pitaFg1" },
    scalaCapitalWord = { link = "pitaFg1" },
    scalaTypeExtension = { link = "pitaFg1" },
    scalaKeyword = { link = "pitaRed" },
    scalaKeywordModifier = { link = "pitaRed" },
    scalaSpecial = { link = "pitaAqua" },
    scalaOperator = { link = "pitaFg1" },
    scalaTypeDeclaration = { link = "pitaYellow" },
    scalaTypeTypePostDeclaration = { link = "pitaYellow" },
    scalaInstanceDeclaration = { link = "pitaFg1" },
    scalaInterpolation = { link = "pitaAqua" },
    markdownItalic = { fg = colors.fg3, italic = true },
    markdownBold = { fg = colors.fg3, bold = config.bold },
    markdownBoldItalic = { fg = colors.fg3, bold = config.bold, italic = true },
    markdownH1 = { link = "pitaGreenBold" },
    markdownH2 = { link = "pitaGreenBold" },
    markdownH3 = { link = "pitaYellowBold" },
    markdownH4 = { link = "pitaYellowBold" },
    markdownH5 = { link = "pitaYellow" },
    markdownH6 = { link = "pitaYellow" },
    markdownCode = { link = "pitaAqua" },
    markdownCodeBlock = { link = "pitaAqua" },
    markdownCodeDelimiter = { link = "pitaAqua" },
    markdownBlockquote = { link = "pitaGray" },
    markdownListMarker = { link = "pitaGray" },
    markdownOrderedListMarker = { link = "pitaGray" },
    markdownRule = { link = "pitaGray" },
    markdownHeadingRule = { link = "pitaGray" },
    markdownUrlDelimiter = { link = "pitaFg3" },
    markdownLinkDelimiter = { link = "pitaFg3" },
    markdownLinkTextDelimiter = { link = "pitaFg3" },
    markdownHeadingDelimiter = { link = "pitaOrange" },
    markdownUrl = { link = "pitaPurple" },
    markdownUrlTitleDelimiter = { link = "pitaGreen" },
    markdownLinkText = { fg = colors.gray, underline = config.underline },
    markdownIdDeclaration = { link = "markdownLinkText" },
    haskellType = { link = "pitaBlue" },
    haskellIdentifier = { link = "pitaAqua" },
    haskellSeparator = { link = "pitaFg4" },
    haskellDelimiter = { link = "pitaOrange" },
    haskellOperators = { link = "pitaPurple" },
    haskellBacktick = { link = "pitaOrange" },
    haskellStatement = { link = "pitaPurple" },
    haskellConditional = { link = "pitaPurple" },
    haskellLet = { link = "pitaRed" },
    haskellDefault = { link = "pitaRed" },
    haskellWhere = { link = "pitaRed" },
    haskellBottom = { link = "pitaRedBold" },
    haskellImportKeywords = { link = "pitaPurpleBold" },
    haskellDeclKeyword = { link = "pitaOrange" },
    haskellDecl = { link = "pitaOrange" },
    haskellDeriving = { link = "pitaPurple" },
    haskellAssocType = { link = "pitaAqua" },
    haskellNumber = { link = "pitaAqua" },
    haskellPragma = { link = "pitaRedBold" },
    haskellTH = { link = "pitaAquaBold" },
    haskellForeignKeywords = { link = "pitaGreen" },
    haskellKeyword = { link = "pitaRed" },
    haskellFloat = { link = "pitaAqua" },
    haskellInfix = { link = "pitaPurple" },
    haskellQuote = { link = "pitaGreenBold" },
    haskellShebang = { link = "pitaYellowBold" },
    haskellLiquid = { link = "pitaPurpleBold" },
    haskellQuasiQuoted = { link = "pitaBlueBold" },
    haskellRecursiveDo = { link = "pitaPurple" },
    haskellQuotedType = { link = "pitaRed" },
    haskellPreProc = { link = "pitaFg4" },
    haskellTypeRoles = { link = "pitaRedBold" },
    haskellTypeForall = { link = "pitaRed" },
    haskellPatternKeyword = { link = "pitaBlue" },
    jsonKeyword = { link = "pitaGreen" },
    jsonQuote = { link = "pitaGreen" },
    jsonBraces = { link = "pitaFg1" },
    jsonString = { link = "pitaFg1" },
    mailQuoted1 = { link = "pitaAqua" },
    mailQuoted2 = { link = "pitaPurple" },
    mailQuoted3 = { link = "pitaYellow" },
    mailQuoted4 = { link = "pitaGreen" },
    mailQuoted5 = { link = "pitaRed" },
    mailQuoted6 = { link = "pitaOrange" },
    mailSignature = { link = "Comment" },
    csBraces = { link = "pitaFg1" },
    csEndColon = { link = "pitaFg1" },
    csLogicSymbols = { link = "pitaFg1" },
    csParens = { link = "pitaFg3" },
    csOpSymbols = { link = "pitaFg3" },
    csInterpolationDelimiter = { link = "pitaFg3" },
    csInterpolationAlignDel = { link = "pitaAquaBold" },
    csInterpolationFormat = { link = "pitaAqua" },
    csInterpolationFormatDel = { link = "pitaAquaBold" },
    rustSigil = { link = "pitaOrange" },
    rustEscape = { link = "pitaAqua" },
    rustStringContinuation = { link = "pitaAqua" },
    rustEnum = { link = "pitaAqua" },
    rustStructure = { link = "pitaAqua" },
    rustModPathSep = { link = "pitaFg2" },
    rustCommentLineDoc = { link = "Comment" },
    rustDefault = { link = "pitaAqua" },
    ocamlOperator = { link = "pitaFg1" },
    ocamlKeyChar = { link = "pitaOrange" },
    ocamlArrow = { link = "pitaOrange" },
    ocamlInfixOpKeyword = { link = "pitaRed" },
    ocamlConstructor = { link = "pitaOrange" },
    LspSagaCodeActionTitle = { link = "Title" },
    LspSagaCodeActionBorder = { link = "pitaFg1" },
    LspSagaCodeActionContent = { fg = colors.green, bold = config.bold },
    LspSagaLspFinderBorder = { link = "pitaFg1" },
    LspSagaAutoPreview = { link = "pitaOrange" },
    TargetWord = { fg = colors.blue, bold = config.bold },
    FinderSeparator = { link = "pitaAqua" },
    LspSagaDefPreviewBorder = { link = "pitaBlue" },
    LspSagaHoverBorder = { link = "pitaOrange" },
    LspSagaRenameBorder = { link = "pitaBlue" },
    LspSagaDiagnosticSource = { link = "pitaOrange" },
    LspSagaDiagnosticBorder = { link = "pitaPurple" },
    LspSagaDiagnosticHeader = { link = "pitaGreen" },
    LspSagaSignatureHelpBorder = { link = "pitaGreen" },
    SagaShadow = { link = "pitaBg0" },
    DashboardShortCut = { link = "pitaOrange" },
    DashboardHeader = { link = "pitaAqua" },
    DashboardCenter = { link = "pitaYellow" },
    DashboardFooter = { fg = colors.purple, italic = true },
    MasonHighlight = { link = "pitaAqua" },
    MasonHighlightBlock = { fg = colors.bg0, bg = colors.blue },
    MasonHighlightBlockBold = { fg = colors.bg0, bg = colors.blue, bold = true },
    MasonHighlightSecondary = { fg = colors.yellow },
    MasonHighlightBlockSecondary = { fg = colors.bg0, bg = colors.yellow },
    MasonHighlightBlockBoldSecondary = { fg = colors.bg0, bg = colors.yellow, bold = true },
    MasonHeader = { link = "MasonHighlightBlockBoldSecondary" },
    MasonHeaderSecondary = { link = "MasonHighlightBlockBold" },
    MasonMuted = { fg = colors.fg4 },
    MasonMutedBlock = { fg = colors.bg0, bg = colors.fg4 },
    MasonMutedBlockBold = { fg = colors.bg0, bg = colors.fg4, bold = true },
    LspInlayHint = { link = "comment" },
    CarbonFile = { link = "pitaFg1" },
    CarbonExe = { link = "pitaYellow" },
    CarbonSymlink = { link = "pitaAqua" },
    CarbonBrokenSymlink = { link = "pitaRed" },
    CarbonIndicator = { link = "pitaGray" },
    CarbonDanger = { link = "pitaRed" },
    CarbonPending = { link = "pitaYellow" },
    NoiceCursor = { link = "TermCursor" },
    NoiceCmdlinePopupBorder = { fg = colors.blue, bg = nil },
    NoiceCmdlineIcon = { link = "NoiceCmdlinePopupBorder" },
    NoiceConfirmBorder = { link = "NoiceCmdlinePopupBorder" },
    NoiceCmdlinePopupBorderSearch = { fg = colors.yellow, bg = nil },
    NoiceCmdlineIconSearch = { link = "NoiceCmdlinePopupBorderSearch" },
    NotifyDEBUGBorder = { link = "pitaBlue" },
    NotifyDEBUGIcon = { link = "pitaBlue" },
    NotifyDEBUGTitle = { link = "pitaBlue" },
    NotifyERRORBorder = { link = "pitaRed" },
    NotifyERRORIcon = { link = "pitaRed" },
    NotifyERRORTitle = { link = "pitaRed" },
    NotifyINFOBorder = { link = "pitaAqua" },
    NotifyINFOIcon = { link = "pitaAqua" },
    NotifyINFOTitle = { link = "pitaAqua" },
    NotifyTRACEBorder = { link = "pitaGreen" },
    NotifyTRACEIcon = { link = "pitaGreen" },
    NotifyTRACETitle = { link = "pitaGreen" },
    NotifyWARNBorder = { link = "pitaYellow" },
    NotifyWARNIcon = { link = "pitaYellow" },
    NotifyWARNTitle = { link = "pitaYellow" },
    IlluminatedWordText = { link = "LspReferenceText" },
    IlluminatedWordRead = { link = "LspReferenceRead" },
    IlluminatedWordWrite = { link = "LspReferenceWrite" },
    TSRainbowRed = { fg = colors.red },
    TSRainbowOrange = { fg = colors.orange },
    TSRainbowYellow = { fg = colors.yellow },
    TSRainbowGreen = { fg = colors.green },
    TSRainbowBlue = { fg = colors.blue },
    TSRainbowViolet = { fg = colors.purple },
    TSRainbowCyan = { fg = colors.aqua },
    RainbowDelimiterRed = { fg = colors.red },
    RainbowDelimiterOrange = { fg = colors.orange },
    RainbowDelimiterYellow = { fg = colors.yellow },
    RainbowDelimiterGreen = { fg = colors.green },
    RainbowDelimiterBlue = { fg = colors.blue },
    RainbowDelimiterViolet = { fg = colors.purple },
    RainbowDelimiterCyan = { fg = colors.aqua },
    DapBreakpointSymbol = { fg = colors.red, bg = colors.bg1 },
    DapStoppedSymbol = { fg = colors.green, bg = colors.bg1 },
    DapUIBreakpointsCurrentLine = { link = "pitaYellow" },
    DapUIBreakpointsDisabledLine = { link = "pitaGray" },
    DapUIBreakpointsInfo = { link = "pitaAqua" },
    DapUIBreakpointsLine = { link = "pitaYellow" },
    DapUIBreakpointsPath = { link = "pitaBlue" },
    DapUICurrentFrameName = { link = "pitaPurple" },
    DapUIDecoration = { link = "pitaPurple" },
    DapUIEndofBuffer = { link = "EndOfBuffer" },
    DapUIFloatBorder = { link = "pitaAqua" },
    DapUILineNumber = { link = "pitaYellow" },
    DapUIModifiedValue = { link = "pitaRed" },
    DapUIPlayPause = { fg = colors.green, bg = colors.bg1 },
    DapUIRestart = { fg = colors.green, bg = colors.bg1 },
    DapUIScope = { link = "pitaBlue" },
    DapUISource = { link = "pitaFg1" },
    DapUIStepBack = { fg = colors.blue, bg = colors.bg1 },
    DapUIStepInto = { fg = colors.blue, bg = colors.bg1 },
    DapUIStepOut = { fg = colors.blue, bg = colors.bg1 },
    DapUIStepOver = { fg = colors.blue, bg = colors.bg1 },
    DapUIStop = { fg = colors.red, bg = colors.bg1 },
    DapUIStoppedThread = { link = "pitaBlue" },
    DapUIThread = { link = "pitaBlue" },
    DapUIType = { link = "pitaOrange" },
    DapUIUnavailable = { link = "pitaGray" },
    DapUIWatchesEmpty = { link = "pitaGray" },
    DapUIWatchesError = { link = "pitaRed" },
    DapUIWatchesValue = { link = "pitaYellow" },
    DapUIWinSelect = { link = "pitaYellow" },
    NeogitDiffDelete = { link = "DiffDelete" },
    NeogitDiffAdd = { link = "DiffAdd" },
    NeogitHunkHeader = { link = "WinBar" },
    NeogitHunkHeaderHighlight = { link = "WinBarNC" },
    DiffviewStatusModified = { link = "pitaGreenBold" },
    DiffviewFilePanelInsertions = { link = "pitaGreenBold" },
    DiffviewFilePanelDeletions = { link = "pitaRedBold" },
    MiniAnimateCursor = { reverse = true, nocombine = true },
    MiniAnimateNormalFloat = { fg = colors.fg1, bg = colors.bg1 },
    MiniClueBorder = { link = "FloatBorder" },
    MiniClueDescGroup = { link = "DiagnosticFloatingWarn" },
    MiniClueDescSingle = { link = "NormalFloat" },
    MiniClueNextKey = { link = "DiagnosticFloatingHint" },
    MiniClueNextKeyWithPostkeys = { link = "DiagnosticFloatingError" },
    MiniClueSeparator = { link = "DiagnosticFloatingInfo" },
    MiniClueTitle = { link = "FloatTitle" },
    MiniCompletionActiveParameter = { underline = true },
    MiniCursorword = { underline = true },
    MiniCursorwordCurrent = { underline = true },
    MiniDepsChangeAdded = { link = "pitaGreen" },
    MiniDepsChangeRemoved = { link = "pitaRed" },
    MiniDepsHint = { link = "DiagnosticHint" },
    MiniDepsInfo = { link = "DiagnosticInfo" },
    MiniDepsMsgBreaking = { link = "DiagnosticWarn" },
    MiniDepsPlaceholder = { link = "Comment" },
    MiniDepsTitle = { link = "Title" },
    MiniDepsTitleError = { link = "DiffDelete" },
    MiniDepsTitleSame = { link = "DiffChange" },
    MiniDepsTitleUpdate = { link = "DiffAdd" },
    MiniDiffOverAdd = { link = "DiffAdd" },
    MiniDiffOverChange = { link = "DiffText" },
    MiniDiffOverContext = { link = "DiffChange" },
    MiniDiffOverDelete = { link = "DiffDelete" },
    MiniDiffSignAdd = { link = "pitaGreen" },
    MiniDiffSignChange = { link = "pitaAqua" },
    MiniDiffSignDelete = { link = "pitaRed" },
    MiniFilesBorder = { link = "FloatBorder" },
    MiniFilesBorderModified = { link = "DiagnosticFloatingWarn" },
    MiniFilesCursorLine = { bg = colors.bg2 },
    MiniFilesDirectory = { link = "Directory" },
    MiniFilesFile = { link = "pitaFg1" },
    MiniFilesNormal = { link = "NormalFloat" },
    MiniFilesTitle = { link = "FloatTitle" },
    MiniFilesTitleFocused = { link = "pitaOrangeBold" },
    MiniHipatternsFixme = { fg = colors.bg0, bg = colors.red, bold = config.bold },
    MiniHipatternsHack = { fg = colors.bg0, bg = colors.yellow, bold = config.bold },
    MiniHipatternsNote = { fg = colors.bg0, bg = colors.blue, bold = config.bold },
    MiniHipatternsTodo = { fg = colors.bg0, bg = colors.aqua, bold = config.bold },
    MiniIconsAzure = { link = "pitaBlue" },
    MiniIconsBlue = { link = "pitaBlue" },
    MiniIconsCyan = { link = "pitaAqua" },
    MiniIconsGreen = { link = "pitaGreen" },
    MiniIconsGrey = { link = "pitaFg0" },
    MiniIconsOrange = { link = "pitaOrange" },
    MiniIconsPurple = { link = "pitaPurple" },
    MiniIconsRed = { link = "pitaRed" },
    MiniIconsYellow = { link = "pitaYellow" },
    MiniIndentscopeSymbol = { link = "pitaGray" },
    MiniIndentscopeSymbolOff = { link = "pitaYellow" },
    MiniJump = { link = "pitaOrangeUnderline" },
    MiniJump2dDim = { link = "pitaGray" },
    MiniJump2dSpot = { fg = colors.orange, bold = config.bold, nocombine = true },
    MiniJump2dSpotAhead = { fg = colors.aqua, bg = colors.bg0, nocombine = true },
    MiniJump2dSpotUnique = { fg = colors.yellow, bold = config.bold, nocombine = true },
    MiniMapNormal = { link = "NormalFloat" },
    MiniMapSymbolCount = { link = "Special" },
    MiniMapSymbolLine = { link = "Title" },
    MiniMapSymbolView = { link = "Delimiter" },
    MiniNotifyBorder = { link = "FloatBorder" },
    MiniNotifyNormal = { link = "NormalFloat" },
    MiniNotifyTitle = { link = "FloatTitle" },
    MiniOperatorsExchangeFrom = { link = "IncSearch" },
    MiniPickBorder = { link = "FloatBorder" },
    MiniPickBorderBusy = { link = "DiagnosticFloatingWarn" },
    MiniPickBorderText = { link = "FloatTitle" },
    MiniPickIconDirectory = { link = "Directory" },
    MiniPickIconFile = { link = "MiniPickNormal" },
    MiniPickHeader = { link = "DiagnosticFloatingHint" },
    MiniPickMatchCurrent = { bg = colors.bg2 },
    MiniPickMatchMarked = { link = "Visual" },
    MiniPickMatchRanges = { link = "DiagnosticFloatingHint" },
    MiniPickNormal = { link = "NormalFloat" },
    MiniPickPreviewLine = { link = "CursorLine" },
    MiniPickPreviewRegion = { link = "IncSearch" },
    MiniPickPrompt = { link = "DiagnosticFloatingInfo" },
    MiniStarterCurrent = { nocombine = true },
    MiniStarterFooter = { link = "pitaGray" },
    MiniStarterHeader = { link = "Title" },
    MiniStarterInactive = { link = "Comment" },
    MiniStarterItem = { link = "Normal" },
    MiniStarterItemBullet = { link = "Delimiter" },
    MiniStarterItemPrefix = { link = "WarningMsg" },
    MiniStarterSection = { link = "Delimiter" },
    MiniStarterQuery = { link = "MoreMsg" },
    MiniStatuslineDevinfo = { link = "StatusLine" },
    MiniStatuslineFileinfo = { link = "StatusLine" },
    MiniStatuslineFilename = { link = "StatusLineNC" },
    MiniStatuslineInactive = { link = "StatusLineNC" },
    MiniStatuslineModeCommand = { fg = colors.bg0, bg = colors.yellow, bold = config.bold },
    MiniStatuslineModeInsert = { fg = colors.bg0, bg = colors.blue, bold = config.bold },
    MiniStatuslineModeNormal = { fg = colors.bg0, bg = colors.fg1, bold = config.bold },
    MiniStatuslineModeOther = { fg = colors.bg0, bg = colors.aqua, bold = config.bold },
    MiniStatuslineModeReplace = { fg = colors.bg0, bg = colors.red, bold = config.bold },
    MiniStatuslineModeVisual = { fg = colors.bg0, bg = colors.green, bold = config.bold },
    MiniSurround = { link = "IncSearch" },
    MiniTablineCurrent = { fg = colors.green, bg = colors.bg1, bold = config.bold, },
    MiniTablineFill = { link = "TabLineFill" },
    MiniTablineHidden = { fg = colors.bg4, bg = colors.bg1, },
    MiniTablineModifiedCurrent = {
      fg = colors.bg1,
      bg = colors.green,
      bold = config.bold,
    },
    MiniTablineModifiedHidden = { fg = colors.bg1, bg = colors.bg4, },
    MiniTablineModifiedVisible = { fg = colors.bg1, bg = colors.fg1, },
    MiniTablineTabpagesection = { link = "Search" },
    MiniTablineVisible = { fg = colors.fg1, bg = colors.bg1, },
    MiniTestEmphasis = { bold = config.bold },
    MiniTestFail = { link = "pitaRedBold" },
    MiniTestPass = { link = "pitaGreenBold" },
    MiniTrailspace = { bg = colors.red },
    ["@comment"] = { link = "Comment" },
    ["@none"] = { bg = "NONE", fg = "NONE" },
    ["@preproc"] = { link = "PreProc" },
    ["@define"] = { link = "Define" },
    ["@operator"] = { link = "Operator" },
    ["@punctuation.delimiter"] = { link = "Delimiter" },
    ["@punctuation.bracket"] = { link = "pitaOrange" },
    ["@punctuation.special"] = { link = "Delimiter" },
    ["@string"] = { link = "String" },
    ["@string.regex"] = { link = "String" },
    ["@string.regexp"] = { link = "String" },
    ["@string.escape"] = { link = "SpecialChar" },
    ["@string.special"] = { link = "SpecialChar" },
    ["@string.special.path"] = { link = "Underlined" },
    ["@string.special.symbol"] = { link = "Identifier" },
    ["@string.special.url"] = { link = "Underlined" },
    ["@character"] = { link = "Character" },
    ["@character.special"] = { link = "SpecialChar" },
    ["@boolean"] = { link = "Boolean" },
    ["@number"] = { link = "Number" },
    ["@number.float"] = { link = "Float" },
    ["@float"] = { link = "Float" },
    ["@function"] = { link = "Function" },
    ["@function.builtin"] = { link = "Special" },
    ["@function.call"] = { link = "Function" },
    ["@function.macro"] = { link = "Macro" },
    ["@function.method"] = { link = "Function" },
    ["@method"] = { link = "Function" },
    ["@method.call"] = { link = "Function" },
    ["@constructor"] = { link = "Special" },
    ["@parameter"] = { link = "Identifier" },
    ["@keyword"] = { link = "Keyword" },
    ["@keyword.conditional"] = { link = "Conditional" },
    ["@keyword.debug"] = { link = "Debug" },
    ["@keyword.directive"] = { link = "PreProc" },
    ["@keyword.directive.define"] = { link = "Define" },
    ["@keyword.exception"] = { link = "Exception" },
    ["@keyword.function"] = { link = "Keyword" },
    ["@keyword.import"] = { link = "Include" },
    ["@keyword.operator"] = { link = "pitaRed" },
    ["@keyword.repeat"] = { link = "Repeat" },
    ["@keyword.return"] = { link = "Keyword" },
    ["@keyword.storage"] = { link = "StorageClass" },
    ["@conditional"] = { link = "Conditional" },
    ["@repeat"] = { link = "Repeat" },
    ["@debug"] = { link = "Debug" },
    ["@label"] = { link = "Label" },
    ["@include"] = { link = "Include" },
    ["@exception"] = { link = "Exception" },
    ["@type"] = { link = "Type" },
    ["@type.builtin"] = { link = "Type" },
    ["@type.definition"] = { link = "Typedef" },
    ["@type.qualifier"] = { link = "Type" },
    ["@storageclass"] = { link = "StorageClass" },
    ["@attribute"] = { link = "PreProc" },
    ["@field"] = { link = "Identifier" },
    ["@property"] = { link = "Identifier" },
    ["@variable"] = { link = "pitaPurple" },
    ["@variable.builtin"] = { link = "Special" },
    ["@variable.member"] = { link = "Identifier" },
    ["@variable.parameter"] = { link = "Identifier" },
    ["@constant"] = { link = "Constant" },
    ["@constant.builtin"] = { link = "Special" },
    ["@constant.macro"] = { link = "Define" },
    ["@markup"] = { link = "pitaFg1" },
    ["@markup.strong"] = { bold = config.bold },
    ["@markup.italic"] = { link = "@text.emphasis" },
    ["@markup.underline"] = { underline = config.underline },
    ["@markup.strikethrough"] = { strikethrough = config.strikethrough },
    ["@markup.heading"] = { link = "Title" },
    ["@markup.raw"] = { link = "String" },
    ["@markup.math"] = { link = "Special" },
    ["@markup.environment"] = { link = "Macro" },
    ["@markup.environment.name"] = { link = "Type" },
    ["@markup.link"] = { link = "Underlined" },
    ["@markup.link.label"] = { link = "SpecialChar" },
    ["@markup.list"] = { link = "Delimiter" },
    ["@markup.list.checked"] = { link = "pitaGreen" },
    ["@markup.list.unchecked"] = { link = "pitaGray" },
    ["@comment.todo"] = { link = "Todo" },
    ["@comment.note"] = { link = "SpecialComment" },
    ["@comment.warning"] = { link = "WarningMsg" },
    ["@comment.error"] = { link = "ErrorMsg" },
    ["@diff.plus"] = { link = "diffAdded" },
    ["@diff.minus"] = { link = "diffRemoved" },
    ["@diff.delta"] = { link = "diffChanged" },
    ["@module"] = { link = "pitaFg1" },
    ["@namespace"] = { link = "pitaFg1" },
    ["@symbol"] = { link = "Identifier" },
    ["@text"] = { link = "pitaFg1" },
    ["@text.strong"] = { bold = config.bold },
    ["@text.emphasis"] = { italic = config.italic.emphasis },
    ["@text.underline"] = { underline = config.underline },
    ["@text.strike"] = { strikethrough = config.strikethrough },
    ["@text.title"] = { link = "Title" },
    ["@text.literal"] = { link = "String" },
    ["@text.uri"] = { link = "Underlined" },
    ["@text.math"] = { link = "Special" },
    ["@text.environment"] = { link = "Macro" },
    ["@text.environment.name"] = { link = "Type" },
    ["@text.reference"] = { link = "Constant" },
    ["@text.todo"] = { link = "Todo" },
    ["@text.todo.checked"] = { link = "pitaGreen" },
    ["@text.todo.unchecked"] = { link = "pitaGray" },
    ["@text.note"] = { link = "SpecialComment" },
    ["@text.note.comment"] = { fg = colors.purple, bold = config.bold },
    ["@text.warning"] = { link = "WarningMsg" },
    ["@text.danger"] = { link = "ErrorMsg" },
    ["@text.danger.comment"] = { fg = colors.fg0, bg = colors.red, bold = config.bold },
    ["@text.diff.add"] = { link = "diffAdded" },
    ["@text.diff.delete"] = { link = "diffRemoved" },
    ["@tag"] = { link = "Tag" },
    ["@tag.attribute"] = { link = "Identifier" },
    ["@tag.delimiter"] = { link = "Delimiter" },
    ["@punctuation"] = { link = "Delimiter" },
    ["@macro"] = { link = "Macro" },
    ["@structure"] = { link = "Structure" },
    ["@lsp.type.class"] = { link = "@type" },
    ["@lsp.type.comment"] = { link = "@comment" },
    ["@lsp.type.decorator"] = { link = "@macro" },
    ["@lsp.type.enum"] = { link = "@type" },
    ["@lsp.type.enumMember"] = { link = "@constant" },
    ["@lsp.type.function"] = { link = "@function" },
    ["@lsp.type.interface"] = { link = "@constructor" },
    ["@lsp.type.macro"] = { link = "@macro" },
    ["@lsp.type.method"] = { link = "@method" },
    ["@lsp.type.modifier.java"] = { link = "@keyword.type.java" },
    ["@lsp.type.namespace"] = { link = "@namespace" },
    ["@lsp.type.parameter"] = { link = "@parameter" },
    ["@lsp.type.property"] = { link = "@property" },
    ["@lsp.type.struct"] = { link = "@type" },
    ["@lsp.type.type"] = { link = "@type" },
    ["@lsp.type.typeParameter"] = { link = "@type.definition" },
    ["@lsp.type.variable"] = { link = "@variable" },
    --custom stuff for me ;)
    MyCmdLineBorder = { fg = colors.blue, bg = colors.bg1, bold = true },
    MySearchBackground = { fg = colors.pitaWhite, bg = colors.bg1, },
    MyCmdLIneTitle = { fg = colors.blue, bg = colors.bg1, bold = true },
    MyCmdLinePrefix = { fg = colors.blue, bg = colors.bg1, bold = true },
  }


  for group, hl in pairs(config.overrides) do
    if groups[group] then
      -- "link" should not mix with other configs (:h hi-link)
      groups[group].link = nil
    end

    groups[group] = vim.tbl_extend("force", groups[group] or {}, hl)
  end

  return groups
end

---@param config PitaConfig?
Pita.setup = function(config)
  Pita.config = vim.tbl_deep_extend("force", Pita.config, config or {})
end

--- main load function
Pita.load = function()
  if vim.version().minor < 8 then
    vim.notify_once("you must use neovim 0.8 or higher")
    return
  end

  -- reset colors
  if vim.g.colors_name then
    vim.cmd.hi("clear")
  end
  vim.g.colors_name = "pitascheme"
  vim.o.termguicolors = true

  local groups = get_groups()

  -- add highlights
  for group, settings in pairs(groups) do
    vim.api.nvim_set_hl(0, group, settings)
  end
end

return Pita
